"""empty message

Revision ID: 1e3cf582615c
Revises:
Create Date: 2021-12-23 04:06:11.405306

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e3cf582615c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "category", ["name"])
    op.create_unique_constraint(None, "species", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "species", type_="unique")
    op.drop_constraint(None, "category", type_="unique")
    # ### end Alembic commands ###
