"""empty message

Revision ID: 630c02d98af2
Revises: edc8768cf681
Create Date: 2022-01-04 11:20:29.673752

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "630c02d98af2"
down_revision = "edc8768cf681"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_animal_category_id", table_name="animal")
    op.drop_index("ix_animal_id", table_name="animal")
    op.drop_index("ix_animal_name", table_name="animal")
    op.drop_index("ix_animal_species_id", table_name="animal")
    op.drop_index("ix_category_id", table_name="category")
    op.drop_index("ix_category_name", table_name="category")
    op.drop_index("ix_species_id", table_name="species")
    op.drop_index("ix_species_name", table_name="species")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_species_name", "species", ["name"], unique=False)
    op.create_index("ix_species_id", "species", ["id"], unique=False)
    op.create_index("ix_category_name", "category", ["name"], unique=False)
    op.create_index("ix_category_id", "category", ["id"], unique=False)
    op.create_index("ix_animal_species_id", "animal", ["species_id"], unique=False)
    op.create_index("ix_animal_name", "animal", ["name"], unique=False)
    op.create_index("ix_animal_id", "animal", ["id"], unique=False)
    op.create_index("ix_animal_category_id", "animal", ["category_id"], unique=False)
    # ### end Alembic commands ###
