"""add unique constraints

Revision ID: 6b7ad8fd60f9
Revises: 630c02d98af2
Create Date: 2022-01-06 08:08:20.834924

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "6b7ad8fd60f9"
down_revision = "630c02d98af2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "animal", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "animal", type_="unique")
    # ### end Alembic commands ###
